[package]
name = "raytracing"
version = "0.1.0"
edition = "2024"

[dependencies]
fork_union = "2.2.9"
rand = "0.9.1"
rand_chacha = "0.9.0"
rayon = "1.10.0"
thiserror = "2.0.12"

[dev-dependencies]
pretty_assertions = "1.4.1"
